openapi: 3.0.0
info:
  title: Transfer
  version: '1.0'
servers:
  - url: 'http://localhost:8000'
    description: local
paths:
  /transfers:
    post:
      summary: ''
      operationId: post-transfers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  transferId:
                    type: string
                    format: uuid
                  status:
                    type: string
                required:
                  - transferId
                  - status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                origin:
                  type: string
                destination:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    minProperties: 1
                    properties:
                      sku:
                        type: string
                      quantity:
                        type: number
                        minimum: 1
                        maximum: 1000
                    required:
                      - sku
                      - quantity
              required:
                - origin
                - destination
                - items
components:
  schemas: {}
